spring.application.name=s59-springboot-mvc-crud-operation-using-db
# MySQL Database Connection
spring.datasource.url=jdbc:mysql://stu-database.clk4q0s8khvr.ap-southeast-2.rds.amazonaws.com:3306/studentdb
spring.datasource.username=admin
spring.datasource.password=Shyam_22289727

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
